// Copyright (c) 2026 The Blade Authors.
// All rights reserved.

// answer.h is generated by the `gen_answer` custom rule (gen_rules.bld) and
// reaches us through the dep's generated_hdrs + the build-dir include path.
#include "suites/custom_rule/answer.h"

#include "suites/test_framework/test_framework.h"

// Compile-time proof the generated header is reachable and correct.
static_assert(CUSTOM_RULE_ANSWER == 42, "custom rule generated header value");

namespace blade_test::custom_rule {

TEST(CustomRule, GeneratedHeaderIsUsable) {
    EXPECT_EQ(42, CUSTOM_RULE_ANSWER);
}

}  // namespace blade_test::custom_rule
